/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Abrahan Barrios
 */
public class FrmCajero extends javax.swing.JFrame {

    String usuario="Cajero";
    int idCajero;

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public int getIdCajero() {
        return idCajero;
    }

    public void setIdCajero(int idCajero) {
        this.idCajero = idCajero;
    }
    
    
    /**
     * Creates new form FrmCajero
     */
    public FrmCajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuCajero = new javax.swing.JMenu();
        opcMnuSalir = new javax.swing.JMenuItem();
        mnuVen = new javax.swing.JMenu();
        opcMnuNuevaV = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        opcMnuAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        mnuCajero.setMnemonic('e');
        mnuCajero.setText("Cajero");

        opcMnuSalir.setMnemonic('x');
        opcMnuSalir.setText("Salir");
        opcMnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMnuSalirActionPerformed(evt);
            }
        });
        mnuCajero.add(opcMnuSalir);

        menuBar.add(mnuCajero);

        mnuVen.setMnemonic('h');
        mnuVen.setText("Venta");

        opcMnuNuevaV.setMnemonic('o');
        opcMnuNuevaV.setText("Nueva");
        opcMnuNuevaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMnuNuevaVActionPerformed(evt);
            }
        });
        mnuVen.add(opcMnuNuevaV);

        menuBar.add(mnuVen);

        mnuAyuda.setText("Ayuda");

        opcMnuAcerca.setText("Acerca De");
        opcMnuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMnuAcercaActionPerformed(evt);
            }
        });
        mnuAyuda.add(opcMnuAcerca);

        menuBar.add(mnuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcMnuNuevaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMnuNuevaVActionPerformed
        // TODO add your handling code here:
        FrmRegistroVentas venta = new FrmRegistroVentas();
        venta.setTipoUsuario(usuario);
        venta.setIdCajero(idCajero);
        escritorio.add(venta).setVisible(true);
    }//GEN-LAST:event_opcMnuNuevaVActionPerformed

    private void opcMnuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMnuAcercaActionPerformed
        // TODO add your handling code here:
        FrmAyuda ayuda = new FrmAyuda();
        escritorio.add(ayuda).setVisible(true);
    }//GEN-LAST:event_opcMnuAcercaActionPerformed

    private void opcMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcMnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuCajero;
    private javax.swing.JMenu mnuVen;
    private javax.swing.JMenuItem opcMnuAcerca;
    private javax.swing.JMenuItem opcMnuNuevaV;
    private javax.swing.JMenuItem opcMnuSalir;
    // End of variables declaration//GEN-END:variables
}
