/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import control.ControlProducto;
import control.ControlProductoVenta;
import control.ControlUsuario;
import control.ControlVenta;
import entidades.Producto;
import entidades.ProductoVenta;
import entidades.Usuario;
import entidades.Venta;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abrahan Barrios
 */
public class FrmRegistroVentas extends javax.swing.JInternalFrame {

    // Atributos Heredados de las ventanas principales
    String tipoUsuario;
    int idAdmin = 1;
    int idCajero;

    //Controladores de prouctos y ventas
    ControlProducto CProducto = new ControlProducto();
    ControlProductoVenta CProductoVenta = new ControlProductoVenta();
    ControlVenta CVenta = new ControlVenta();
    ControlUsuario CUsuario = new ControlUsuario();

    List<ProductoVenta> productosVenta = new ArrayList<>();

    Venta venta = new Venta();

    float total = 0;
    float subtotal = 0;
    float iva = 0;

    public String getTipoUsuario() {
        return tipoUsuario;
    }

    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public int getIdAdmin() {
        return idAdmin;
    }

    public void setIdAdmin(int idAdmin) {
        this.idAdmin = idAdmin;
    }

    public int getIdCajero() {
        return idCajero;
    }

    /**
     * Creates new form FrmVenta
     */
    public void setIdCajero(int idCajero) {
        this.idCajero = idCajero;
    }

    /**
     * Creates new form FrmVentas
     */
    public FrmRegistroVentas() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        btnCancelar = new javax.swing.JButton();
        txtClaveProducto = new javax.swing.JTextField();
        lblLista = new java.awt.Label();
        txtCantidad = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        txtTotal = new javax.swing.JTextField();
        BtnAgregarProducto = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        BtnTerminar = new javax.swing.JButton();
        lblCant = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblListaVenta = new javax.swing.JTable();
        label3 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        lblVenta = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Venta");
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        escritorio.setBackground(new java.awt.Color(151, 157, 172));

        btnCancelar.setBackground(new java.awt.Color(3, 83, 164));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtClaveProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveProductoActionPerformed(evt);
            }
        });

        lblLista.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblLista.setForeground(new java.awt.Color(0, 18, 51));
        lblLista.setText("LISTA DE VENTA");

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Código de Producto");

        BtnAgregarProducto.setBackground(new java.awt.Color(3, 83, 164));
        BtnAgregarProducto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarProducto.setText("Agregar");
        BtnAgregarProducto.setToolTipText("Escanee un producto para agregarlo");
        BtnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarProductoActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 18, 51));
        lblTotal.setText("Total");

        BtnTerminar.setBackground(new java.awt.Color(3, 83, 164));
        BtnTerminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BtnTerminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnTerminar.setText("Terminar");
        BtnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTerminarActionPerformed(evt);
            }
        });

        lblCant.setBackground(new java.awt.Color(0, 0, 0));
        lblCant.setForeground(new java.awt.Color(0, 0, 0));
        lblCant.setText("Unidades / Peso (Kg)");

        TblListaVenta.setBackground(new java.awt.Color(125, 133, 151));
        TblListaVenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TblListaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Nombre de Producto", "Precio Unitario"
            }
        ));
        jScrollPane1.setViewportView(TblListaVenta);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Cantidad");

        jPanel1.setBackground(new java.awt.Color(0, 40, 85));

        lblVenta.setAlignment(java.awt.Label.CENTER);
        lblVenta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblVenta.setText("VENTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 65, 92));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Coca Cola 600ml");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("18.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar1.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setText("Eliminar");
        btnCancelar1.setToolTipText("(i) Seleccione un producto de la lista de venta");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        escritorio.setLayer(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(txtClaveProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblLista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(txtCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(label2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(txtTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(BtnAgregarProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(BtnTerminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblCant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(label3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnCancelar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelar1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCant))
                            .addComponent(txtClaveProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(lblLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(BtnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnCancelar)
                .addGap(75, 75, 75)
                .addComponent(BtnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCant))))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClaveProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addComponent(lblLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        label2.getAccessibleContext().setAccessibleName("Codigo de Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTerminarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea terminar la venta?", "Confirmación", 2) == 0) {

            if (TblListaVenta.getRowCount() > 0) {
                try {

                    //Verificar si algun producto tiene promocion

                    //Agregar la venta a la base de datos\
                    venta.setTotal(total);

                    GregorianCalendar fecha = new GregorianCalendar();

                    venta.setFecha(fecha.getTime());

                    Usuario user = CUsuario.consultarPorIdUsuario(1);
                    System.out.println("Usuario > "+user.getIdUsuario());
                    venta.setIdUsuario(user);

                    //                    venta.setProductoVentaList(productosVenta);
                    CVenta.guardarVenta(venta);

                    System.out.println("ID Venta: " + venta.getIdVenta());

                    //Agregar productos de venta a la base de datos
                    for (int i = 0; i < productosVenta.size(); i++) {

                        ProductoVenta v = productosVenta.get(i);
                        Producto p = CProducto.consultarPorCodigo(productosVenta.get(i).getIdProducto().getCodigo());
                        float cantidad = v.getCantidad();
                        p.setStock(p.getStock()- cantidad);

                        v.setVenta(venta);
                        
                        System.out.println(v.getVenta());

                        try {
                            CProducto.actualizarProducto(p);

                        } catch (PersistenceException e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                        try {
                            CProductoVenta.guardarProductoVenta(v);

                        } catch (PersistenceException e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }

                    }
                    
                    JOptionPane.showMessageDialog(this, "Venta finalizada con éxito. Folio: "
                            + venta.getIdVenta() + " Total: " + venta.getTotal(), "Venta finalizada", JOptionPane.INFORMATION_MESSAGE);


                    txtClaveProducto.setText("");
                    txtCantidad.setText("");
                    txtClaveProducto.grabFocus();

                    this.dispose();

                } catch (PersistenceException e) {
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al hacer la venta " + e.getMessage(), "Lo sentimos", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    Logger.getLogger(FrmRegistroVentas.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Lista de venta vacia, agregue Productos");
                txtClaveProducto.setText("");
                txtCantidad.setText("");
                txtClaveProducto.grabFocus();

            }
        }
    }//GEN-LAST:event_BtnTerminarActionPerformed

    private void BtnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarProductoActionPerformed
        if (txtClaveProducto.getText().equals("") || txtCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos");
        } else {

            DefaultTableModel modelo = (DefaultTableModel) TblListaVenta.getModel();
            Producto producto;

            //Sección 2
            Object[] fila = new Object[3];
            String claveProducto = "";
            float cantidad = 0;

            try {
                //Inicializar parametros de agregar producto
                claveProducto = txtClaveProducto.getText();
                cantidad = Float.parseFloat(txtCantidad.getText());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Llenado fallido de los campos, intente de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
                txtClaveProducto.setText("");
                txtCantidad.setText("");
                txtClaveProducto.grabFocus();
                return;

            }
            //Verificar que el producto exista
            if (CProducto.consultarPorCodigo(claveProducto) != null) {
                if (CProducto.consultarPorCodigo(claveProducto).getStock() < cantidad) {
                    JOptionPane.showMessageDialog(this, "No se cuenta con suficientes articulos de este producto", "Error", JOptionPane.ERROR_MESSAGE);
                } else {

                    //Cr
                    producto = CProducto.consultarPorCodigo(claveProducto);

                    String nombreProducto = "";
                    float precioUnitario = 0.0f;

                    try {
                        nombreProducto = producto.getNombre();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "No se encontro el nombre del producto con la clave solicitada");
                        return;
                    }

                    try {

                        precioUnitario = producto.getPrecio();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "No se encontro el precio unitario del producto con la clave solicitada");
                        return;

                    }

                    //Sección 3
                    fila[0] = txtCantidad.getText();
                    fila[1] = nombreProducto;
                    fila[2] = precioUnitario;

                    //Sección 4
                    //Sección 5
                    // Almacenamiento de los detalles del producto vendido
                    ProductoVenta p = new ProductoVenta();
                    p.setCantidad((int) cantidad);
                    p.setIdProducto(producto);
                    p.setImporte(cantidad*p.getIdProducto().getPrecio());
                    p.setPrecio(p.getIdProducto().getPrecio());

                    //Validacion de que no se repitan los productos
                    int productoIgual = 0;

                    for (int i = 0; i < productosVenta.size(); i++) {
                        ProductoVenta prodLista = productosVenta.get(i);

                        if (prodLista.getIdProducto() == p.getIdProducto()) {

                            productoIgual = 1;
                            float sumaCantidades = prodLista.getCantidad() + p.getCantidad();
                            float sumaImportes = prodLista.getImporte() + p.getImporte();

                            if (sumaCantidades <= p.getIdProducto().getStock()) {

                                p.setCantidad(sumaCantidades);
                                p.setImporte(sumaImportes);
                                productosVenta.remove(i);
                                JOptionPane.showMessageDialog(null, "Las cantidaes de los productos repetidos han sido sumadas");
                                break;
                            } else {
                                JOptionPane.showMessageDialog(null, "No puede agregar este producto de nuevo, no hay suficiente stock");
                                return;
                            }
                        }

                    }

                    productosVenta.add(p);

                    subtotal += precioUnitario * cantidad;
                    total = subtotal;

                    txtTotal.setText(Float.toString(total));

                    txtClaveProducto.setText("");
                    txtCantidad.setText("");
                    txtClaveProducto.grabFocus();

                    if (productoIgual == 0) {
                        modelo.addRow(fila);
                        TblListaVenta.setModel(modelo);
                    } else {

                        for (int i = 0; i < TblListaVenta.getRowCount(); i++) {
                            if (TblListaVenta.getValueAt(i, 1).toString().equalsIgnoreCase(p.getIdProducto().getNombre())) {

                                TblListaVenta.setValueAt(p.getCantidad(), i, 0);
                                break;
                            }
                        }

                        JOptionPane.showMessageDialog(null, "Productos repetidos, se actualizó la cantidad en la lista",
                                "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {

                //                JOptionPane.showMessageDialog(this, "Producto no encontrado, ingrese una clave valida",
                //                        "Error", JOptionPane.ERROR_MESSAGE);
                if (JOptionPane.showConfirmDialog(null, "Producto no encontrado, desea registrarlo? (ADMINISTRADOR)") == 0) {

//                    Usuario user = CUsuario.consultarPorIdUsuario(idAdmin);
//                    if (user != null&&user.getAdministrador()) {
                    FrmRegistroProductoB p = new FrmRegistroProductoB();
                    this.escritorio.add(p).setVisible(true);
//
//                    } else {
//                        JOptionPane.showMessageDialog(this, "No puede registrar un producto",
//                                "Error", JOptionPane.ERROR_MESSAGE);
//                    }

                }

            }
        }
    }//GEN-LAST:event_BtnAgregarProductoActionPerformed

    private void txtClaveProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea cancelar la venta?", "Confirmación", 2) == 0) {
            this.dispose();

        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Seccion para registrar ventas");
    }//GEN-LAST:event_formAncestorAdded

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarProducto;
    private javax.swing.JButton BtnTerminar;
    private javax.swing.JTable TblListaVenta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel lblCant;
    private java.awt.Label lblLista;
    private javax.swing.JLabel lblTotal;
    private java.awt.Label lblVenta;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtClaveProducto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
